export const LATEST_NEWS = 'LATEST_NEWS';
export const LATEST_NEWS_REQUEST = 'LATEST_NEWS_REQUEST';
export const LATEST_NEWS_SUCCESS = 'LATEST_NEWS_SUCCESS';
export const LATEST_NEWS_FAILURE = 'LATEST_NEWS_FAILURE';
